/* Start.js
 * ===============================
 * The application's start up script. To run your application
 * execute this script in the terminal using the command:
 *		$ node start
 *
 * Please do not edit this file!
*/

// Autoloader for the modules. If you moved the modules folder you
// can update the link to the relevant folder here.
require('./libs/loaders/module.js')(__dirname + '/modules')
var app = require('./libs/index.js')


app.start()
