/* Start.js
 * ===============================
 * The application's start up script. To run your application
 * execute this script in the terminal using the command:
 *		$ node start
 *
 * Please do not edit this file!
*/

var app = require('./libs/index.js')

require('./libs/loaders/module.js')(__dirname + '/modules')

console.log(pyro.AnotherSample({},{}))
// app.start()
